import Head from "next/head";
import React from "react";
import Card from 'react-bootstrap/Card';
import Container from "react-bootstrap/Container";
import Navbar from "react-bootstrap/Navbar";
import Nav from 'react-bootstrap/Nav';
import styles from "../styles/Home.module.css";
import { Row , Col} from "react-bootstrap";
import Link from "next/link";
export const getStaticProps = async () => {
  const res = await fetch(
    "http://ec2-3-110-123-68.ap-south-1.compute.amazonaws.com:3000/api/horror"
  );
  const data = await res.json();
  return {
    props: { results: data },
  };
};
export default function Home({ results }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        />
      </Head>
      <Navbar className={styles.navbar} fixed="top" bg="dark" variant="dark">
        <Container >
          <Navbar.Brand href="#home">Admin Panel</Navbar.Brand>
         
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
        <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="me-auto">
          <Link className={styles.link} href={"/add"}>Add New Data</Link>
          </Nav>
        </Navbar.Collapse>
        </Container>
      </Navbar>
      <main className={styles.main}>
      <Row>
        {results.map((result) => (
          <>
         
            <Col>
            <Card style={{ width: '18rem', marginTop: '2rem' }}>
      <Card.Img width={250} height={350} variant="top" src={result.image} />
      <Card.Body>
        <Card.Title>{result.name}</Card.Title>
        <Card.Text>
        Rating - {result.rating} 
        </Card.Text>
        <Card.Text>
        Released Year - {result.release_year}

        </Card.Text>
  
      </Card.Body>
    </Card>
            </Col>
          
      
 
          </>
        ))}
            </Row>
      </main>
    </>
  );
}
